site:
  title: Payara Community Documentation
  start_page: docs::Overview.adoc
content:
  sources:
    - url: .
      start_path: docs
      branches: HEAD
    - url: .
      start_path: community/docs
      branches: HEAD
asciidoc:
  attributes:
    attribute-missing: 'skip'
    page-site-edition: 'community'
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
runtime:
  fetch: true
output:
    dir: ./build/community/html
antora:
  extensions:
  - '@antora/lunr-extension'